import type { Metadata } from 'next';
import './globals.css';
import { Scheherazade_New, Figtree } from "next/font/google";

const scheherazadeNew = Scheherazade_New({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-scheherazade-new",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${scheherazadeNew.variable} ${figtree.variable}`}>
      <body className="bg-background">
        <main>{children}</main>
      </body>
    </html>
  );
}
