import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Scheherazade_New, Figtree } from "next/font/google";

const scheherazadeNew = Scheherazade_New({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-scheherazade-new",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-figtree",
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${scheherazadeNew.variable} ${figtree.variable}`}>
      <body>
      <Navbar />
      <main>{children}</main>
     </body>
    </html>
  );
}
